### ISSUE TITLE
Missing dependency 'vinyl-source-stream'

### ISSUE THREAD

**Issue by bluerabbit** [na2hiro/json-kifu-format#24]
## エラー内容

gulp buildすると下記のエラーが発生しました

```
%gulp build

Error: Cannot find module 'vinyl-source-stream'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/path/to/.ghq/github.com/na2hiro/json-kifu-format/gulpfile.js:8:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

## 原因

https://github.com/na2hiro/json-kifu-format/blob/master/gulpfile.js#L8 で使っているモジュールがpackage.jsonに含まれていないようです。

- https://github.com/na2hiro/json-kifu-format/blob/master/package.json#L29-L42

## 対応

```
npm install vinyl-source-stream --save-dev
```

でpackage.jsonを更新すればビルドできました。

**Comment by na2hiro** [comment]
ありがとうございます．そのように修正します．

**Comment by na2hiro** [comment]
あ，されてました．
